include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_put_control_body_on_new_line
    - avoid_print
    - directives_ordering
    - lines_longer_than_80_chars
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_expression_function_bodies
    - sort_constructors_first
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_brace_in_string_interps
    - unnecessary_this
